blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a Question
    url: https://github.com/NachoMtnz/Portfolio/discussions/categories/q-a
    about: Ask and answer Portfolio related questions.
  - name: 📖 Read the documentation
    url: https://github.com/NachoMtnz/Portfolio/blob/master/README.md
    about: Please consult the documentation before opening any issues!
